services:
  theezy-art-app:
    build: .
    container_name: theezy-art-app
    ports:
      - "8087:8087"
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8087/api/admin/viewAllArtworks",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
